# Dockerfile.dev
FROM node:22-bookworm-slim

WORKDIR /app

# Copier les fichiers de package
COPY package*.json ./
RUN npm install

# Copier le code source
COPY . .

# Installer les dépendances manquantes
RUN npm install --save-dev autoprefixer postcss tailwindcss

EXPOSE 3000

ENV CHOKIDAR_USEPOLLING=true
ENV VITE_HOST=0.0.0.0

CMD ["npm", "run", "dev"]